### ISSUE TITLE
Object.assign not work in ie 11

### ISSUE THREAD

**Issue by zhangwei8607** [ccnokes/react-toggle-display#5]
Object.assign not work in ie 11

function pickProps(props) {
		var newProps = Object.assign({}, props);
		propsToRemove.forEach(function (prop) {
			if (prop in newProps) {
				delete newProps[prop];
			}
		});
		return newProps;
	}

**Comment by ccnokes** [comment]
Yeah, IE11 is silly. Rather than do something like include my Object.assign polyfill I recommend you just include this in your babel build https://babeljs.io/docs/usage/polyfill/ (or some other global Object.assign polyfill, like maybe https://github.com/zloirock/core-js). I think that's the leanest, most straight-forward way and kind of a standard in the community.

**Comment by zhangwei8607** [comment]
It worked, thanks very much. Actually I am very new to js developer, very appreciate your work.
